import operator from "./operator.json";

export const legalReady = operator.verified && !!operator.name.trim() && !!operator.country.trim() && !!operator.address.trim();
export const legalDate = "2026-09-08";
export const legalContact = operator.email;
const identity = legalReady
  ? `${operator.name}, ${operator.country}.${operator.registration ? ` Registration: ${operator.registration}.` : ""}`
  : "Operator identity and postal address are awaiting confirmation. This document is a draft and must not be submitted as a final store policy.";
// Keep the full postal address in one public legal notice, not in marketing copy.
const postalIdentity = legalReady
  ? `${operator.name}, ${operator.address}, ${operator.country}.${operator.registration ? ` Registration: ${operator.registration}.` : ""}`
  : identity;
const operatorDetails = { label: "Postal address and legal details", href: "/legal#identity" };
export type LegalSection = { id: string; title: string; paragraphs: string[]; links?: { label: string; href: string }[] };
export type LegalDocument = { title: string; summary: string; sections: LegalSection[] };
export const legalDocuments: Record<string, LegalDocument> = {
  privacy: {
    title: "Privacy policy",
    summary: "How AirCapital handles information on the website and in the iOS and Android apps, and how you can exercise your rights.",
    sections: [
      { id: "controller", title: "1. Who is responsible", paragraphs: [identity, `AirCapital is the product name. The operator above is responsible for the processing described here. Contact: ${operator.email}. This policy covers aircapital.app and the AirCapital apps (package tim.AirCapital). Exchanges and app stores have their own responsibilities and privacy policies.`], links: [operatorDetails] },
      { id: "device", title: "2. Your exchange data stays under your control", paragraphs: ["The apps store connected account labels, balances, asset allocations, portfolio history, deposits, withdrawals and related preferences locally. API credentials are held in the device’s secure storage. Financial records are encrypted locally with a key in secure storage. We do not operate an AirCapital server that receives your exchange credentials or portfolio records.", "When you request synchronisation, the app sends authenticated HTTPS requests directly to the exchange you selected. The exchange receives the authentication information required by its API and your network IP address. A public Coinbase price endpoint may also receive a request and IP address for currency conversion. We do not send your portfolio or exchange credentials to that price endpoint. These services process requests under their own policies.", "The operating system performs optional biometric authentication. AirCapital receives the authentication result, not your fingerprint, face image or biometric template. The website demo uses fictional portfolio data and does not accept exchange API keys."] },
      { id: "purposes", title: "3. What we process and why", paragraphs: ["App functionality: the local processing and direct exchange requests described above provide the monitoring service you request (Article 6(1)(b) GDPR). Connecting an exchange is optional; without it, you can use the demo. We do not use portfolio data for advertising or automated decisions about you.", "Website delivery and security: our hosting provider Railway processes connection information such as IP address, request time, requested URL, browser information and response status to deliver pages, diagnose failures and protect the service. Our legal basis is our legitimate interest in providing a reliable and secure website (Article 6(1)(f)).", "Support and privacy requests: if you email us, we receive your email address, message and anything you choose to attach, through our email provider Google. We use this to respond to your request, on the basis of providing requested support, our legitimate interest in resolving enquiries, or compliance with legal obligations for rights requests (Articles 6(1)(b), (f) or (c), as applicable). Please do not send API secrets, identity documents or complete portfolio exports unless a specific, necessary and secure process has first been agreed.", "Optional analytics: only if you agree, Google Analytics on the website and Google Analytics for Firebase in the apps process pseudonymous browser or app-instance identifiers, visits or screen views, session and engagement events, device/browser/OS information, language and approximate location derived from network information. Website demo interactions and store-button clicks are also measured. This uses consent (Article 6(1)(a)). Precise GPS location is not requested. We do not send account labels, balances, transaction records, API keys, email addresses or a developer-assigned user ID to Analytics. Advertising identifiers and Google signals are disabled in our configuration."] },
      { id: "choice", title: "4. Your choice about analytics", paragraphs: ["On the website, the Google tag is blocked until you accept analytics. Accept and reject are both available. You can change your choice through Cookie settings in the footer. On iOS and Android, analytics collection is disabled by default and can be changed in Settings. Declining does not prevent monitoring or use of the demo.", "Withdrawal stops future analytics collection and clears the relevant website analytics cookies or resets the local app analytics identifier. It does not automatically erase events already sent to Google. Withdrawal does not affect the lawfulness of processing before you withdrew. Contact us about deletion of identifiable historical data; we may need limited information to locate a pseudonymous record, and do not collect extra identity data solely to identify it."] },
      { id: "retention", title: "5. How long information is kept", paragraphs: ["Local portfolio history and credentials remain on the device until you remove the relevant connection or use the app’s Delete all data action. Different deletion actions have different scope; see the deletion guide. Clearing browser storage removes website preferences. Uninstalling an app alone may not remove secure-storage entries or copies managed by the operating system.", "Website analytics consent is valid for 180 days before we ask again. Language preferences remain until changed or browser storage is cleared. Google analytics cookies have a default expiry of up to two years, which Google may refresh on use. Browsers may shorten this period.", "Our Google Analytics property is configured for two months of event-level retention and 14 months of user-level retention, with the user period renewed on new activity. Google’s scheduled deletion processes apply; these controls do not limit the lifetime of aggregate reports. Provider security, billing and legal records may follow separate periods described in the provider’s policy.", "We keep support messages while needed to resolve the enquiry and handle a related dispute or legal requirement. We review retained correspondence and remove messages no longer needed. Hosting logs are retained for the provider’s applicable operational retention period and, where necessary, for investigating a specific security incident. You can ask us for the current retention details applicable to your request."] },
      { id: "recipients", title: "6. Providers and international processing", paragraphs: ["Railway provides website hosting. Google provides optional website/app analytics and the email service used for support. Apple and Google provide app distribution and process store-related information under their own terms. Connected exchanges independently process your direct API requests. We do not sell personal data or run an advertising network in the app.", "Providers may process information outside the EEA, including in the United States. Their contractual documentation describes applicable transfer mechanisms, such as adequacy decisions or standard contractual clauses, depending on the service and recipient. Contact us for details of the safeguards applying to processing on our behalf and how to obtain a copy. We do not promise that all provider processing takes place in the EU."], links: [{label:"Railway data processing terms",href:"https://railway.com/legal/dpa"},{label:"Railway privacy policy",href:"https://railway.com/legal/privacy"},{label:"Firebase privacy and security",href:"https://firebase.google.com/support/privacy"},{label:"Google privacy policy",href:"https://policies.google.com/privacy"}] },
      { id: "rights", title: "7. Your rights", paragraphs: [`Depending on the applicable conditions, you can request access, correction, deletion, restriction, portability, or object to processing based on legitimate interests. You may withdraw consent at any time. Send requests to ${operator.email}; you do not need to create an account or pay a fee for an ordinary request. We normally respond within one month. If a lawful extension is needed because of complexity or number of requests, we will explain it within that first month.`, "We may request proportionate verification when necessary to avoid disclosing someone else’s data. We cannot retrieve records stored only on your device or erase records held independently by an exchange. You may complain to the supervisory authority in your EEA country of habitual residence, workplace or the place of the alleged infringement. This does not require contacting us first."], links: [{label:"EEA data protection authorities",href:"https://www.edpb.europa.eu/about-edpb/about-edpb/members_en"},{label:"How to delete your data",href:"/data-deletion"}] },
      { id: "backups", title: "8. Backups and security", paragraphs: ["Export is an action you control. The exported JSON contains portfolio information and account labels, but not API keys or secrets. Exported files are not encrypted by AirCapital. The temporary sharing file is removed when sharing finishes; copies you save or share remain under your control and the recipient’s rules. Protect those copies and delete them separately when no longer needed.", "Device encryption, secure credential storage, HTTPS and optional biometric protection reduce risks but do not eliminate them. Protect your device, use read-only exchange keys, and revoke compromised keys at the exchange. No support request should require you to reveal an API secret."] },
      { id: "other", title: "9. Children, decisions and changes", paragraphs: ["AirCapital is a portfolio monitoring utility and is not directed specifically at children. Exchange account eligibility is governed by each exchange and applicable law. If you believe a child has sent us personal information without the required permission, contact us so we can assess and address it.", "We do not make solely automated decisions producing legal or similarly significant effects about you. Changes to this policy will be dated on this page. We will seek new consent where a change to optional processing requires it."] },
    ],
  },
  cookies: {
    title: "Cookies and analytics",
    summary: "Essential preferences, optional measurement and how to change your choice.",
    sections: [
      {id:"preferences",title:"Website preferences",paragraphs:["The site uses browser local storage to remember your language (aircapital.website.language) and analytics choice (aircapital.web.analytics.v1). A legacy language preference may be read when present. Language remains until changed or cleared; analytics consent expires after 180 days. These preferences are used to respect your choices and are not advertising identifiers."]},
      {id:"analytics",title:"Optional Google Analytics",paragraphs:["Only after acceptance, our website loads the Google tag for G-BLV9ZEBKW9. Google may set _ga and _ga_* cookies to distinguish browsers and sessions. Their default expiry can be up to two years and may be renewed on use. They support visit, engagement and demo-interaction measurement. Advertising storage, ad personalisation and Google signals are disabled.","Before acceptance, we do not load the Google tag or send analytics events to Google. Rejecting analytics keeps the site and demo usable. Hosting requests needed to deliver the page still occur."]},
      {id:"change",title:"Change or withdraw your choice",paragraphs:["Use Cookie settings in the footer, then choose Reject analytics or Accept analytics. Rejection stops further collection and removes the site’s _ga cookies where the browser permits. You can also clear cookies and local storage through your browser. Removing the consent record causes the site to ask again.","Withdrawing consent does not automatically delete previously received analytics events. See the privacy policy and deletion guide for requests concerning historical data."],links:[{label:"Privacy policy",href:"/privacy"},{label:"Data deletion",href:"/data-deletion"}]},
      {id:"apps",title:"iOS and Android",paragraphs:["The native apps use Google Analytics for Firebase, not website cookies. Collection starts only after you opt in. You can switch it off in the app’s Settings. Balances and exchange API keys are not sent to Analytics. The full privacy policy explains device identifiers and retention."]},
    ],
  },
  "data-deletion": {
    title: "Delete your data",
    summary: "AirCapital has no developer-hosted user account. You can remove local data yourself and request deletion of information we hold.",
    sections: [
      {id:"local",title:"1. Delete data on your device",paragraphs:["Open AirCapital → Settings → Privacy and data → Delete all data. Confirm the action. The app removes local exchange accounts, credentials, balances, history, cash-flow records, cached observations and app preferences. It also withdraws optional analytics consent and resets the local analytics identifier. This action cannot be undone; export only if you want to keep a separate copy.","To remove one connection, use its delete action in Settings. To stop the exchange accepting the key altogether, also revoke that API key in the exchange’s own API settings. Deleting local data does not close your exchange account or move your assets."]},
      {id:"copies",title:"2. Remove exported or system-managed copies",paragraphs:["Delete any JSON exports you saved, shared or stored in a cloud drive. Manage device backups through the operating system or backup provider. AirCapital cannot erase copies outside the app. Use the app’s deletion action before uninstalling, because secure-storage or backup entries may otherwise remain."]},
      {id:"website",title:"3. Clear website data",paragraphs:["Use Cookie settings in the footer to reject analytics. Clear site cookies and local storage in your browser to remove language and consent preferences. The web demo contains fictional data, so there is no real portfolio to delete on the website."]},
      {id:"request",title:"4. Ask us to delete information we hold",paragraphs:[`Email ${operator.email} with the subject “AirCapital data deletion”. Describe the information to remove, such as a previous support conversation or optional analytics records. For a support request, sending from the same email address usually helps us locate it. Do not send exchange API keys, passwords or a full financial export.`,"We normally respond within one month and explain any permitted extension. We delete information we can identify and no longer need to keep. Where a legal obligation or necessary legal claim prevents deletion, we explain what is retained and why. Some analytics information is pseudonymous; we may need limited additional information to locate it, and cannot promise to identify a record from your email address alone. Anonymous aggregate reports cannot be traced back to an individual.","Exchange and app-store records must be managed with the respective provider. We cannot delete data controlled independently by those services."],links:[{label:"Email a deletion request",href:`mailto:${operator.email}?subject=AirCapital%20data%20deletion`},{label:"Privacy policy and your rights",href:"/privacy"}]},
    ],
  },
  terms: {
    title: "Terms of use",
    summary: "What AirCapital provides and the conditions for using the website and monitoring apps.",
    sections: [
      {id:"operator",title:"1. The service and its operator",paragraphs:[identity,`Questions or complaints: ${operator.email}. AirCapital provides a website, a fictional web demo and iOS/Android tools for viewing exchange balances. No AirCapital user account is required.`],links:[operatorDetails]},
      {id:"scope",title:"2. Monitoring your own accounts",paragraphs:["AirCapital helps you view balances, allocations, history, deposits and withdrawals from supported exchanges. It does not execute trades, initiate withdrawals, exchange currencies, hold funds or private wallet keys, or provide investment, tax or legal advice. Funds remain with the relevant exchange.","Use only accounts you are authorised to access. Create API credentials with reading permissions only and follow the exchange’s rules. You remain responsible for your exchange account, device security and the permissions granted to your keys. Do not use the service to bypass access controls, interfere with systems or violate another person’s rights."]},
      {id:"accuracy",title:"3. Understanding the figures",paragraphs:["Exchange APIs may be delayed, unavailable or incomplete, and supported wallets and history periods differ. Displayed values may use estimated prices, rounding and cached observations. Deposits and withdrawals can change the portfolio value without representing an investment gain or loss. Demo figures are fictional.","Check material figures against the exchange’s own records before acting. AirCapital does not guarantee returns, continuous API availability or complete transaction history."]},
      {id:"privacy",title:"4. Data and your choices",paragraphs:["The privacy policy explains local storage, direct exchange connections, optional analytics, support correspondence and your rights. Analytics consent is separate from these terms and can be declined. Backups are optional and exported files are not encrypted by AirCapital."],links:[{label:"Privacy policy",href:"/privacy"},{label:"Delete your data",href:"/data-deletion"}]},
      {id:"stores",title:"5. Distribution and charges",paragraphs:["AirCapital is offered as a paid download with a base price of USD 4.99. The applicable local price, currency and taxes are shown by your app store before purchase. The current app has no AirCapital subscription or in-app purchase. The website demo is free. Any future paid feature will be described with its price and applicable conditions before purchase. Your exchange and internet provider may apply their own charges.","App-store payments, receipts and refund requests are handled through the store where you purchased the app. Follow its refund process. Nothing here excludes statutory withdrawal rights, remedies for non-conforming digital content or other mandatory consumer rights. Apps downloaded from Apple are also subject to Apple’s applicable standard licence and store terms. Google Play distribution is subject to its applicable store terms."],links:[{label:"Apple standard licence",href:"https://www.apple.com/legal/internet-services/itunes/dev/stdeula/"}]},
      {id:"rights",title:"6. Intellectual property and third parties",paragraphs:["You may use AirCapital for its intended purpose. AirCapital’s design and original content belong to their respective rights holders. Exchange names and marks identify supported integrations and remain the property of their owners; their appearance does not mean endorsement or affiliation. Third-party software retains its own licence terms."]},
      {id:"availability",title:"7. Changes, stopping use and liability",paragraphs:["The service may change to address security, compatibility or exchange API changes. We will describe material changes and any new paid conditions before they apply. You may stop using AirCapital at any time, remove its local data and revoke your exchange keys.","To the extent permitted by applicable law, we are not responsible for losses caused solely by an exchange outage, an exchange’s actions or misuse of your credentials outside our control. Nothing in these terms excludes liability that cannot lawfully be excluded, liability for intentional misconduct or gross negligence where protected, or mandatory consumer remedies. These terms do not waive statutory conformity, withdrawal or other consumer rights that may apply to digital services."]},
      {id:"disputes",title:"8. Questions and disputes",paragraphs:[`Contact ${operator.email} so we can try to resolve a concern. This does not prevent you from using a competent court, consumer body or data protection authority. These terms do not deprive consumers in the EEA of mandatory protections or the right to bring proceedings where the law allows. No compulsory arbitration clause is imposed.`]},
    ],
  },
  legal: {
    title: "Legal notice",
    summary: "The operator of AirCapital and official contact information.",
    sections: [
      {id:"identity",title:"Operator",paragraphs:[postalIdentity,`Product: AirCapital. Website: https://aircapital.app. Email: ${operator.email}.`]},
      {id:"contact",title:"Contact",paragraphs:["Use this email for support, complaints, privacy requests and legal correspondence. Include enough context for us to answer, but do not include exchange passwords or API secrets."],links:[{label:"Contact AirCapital",href:`mailto:${operator.email}`}]},
      {id:"service",title:"Nature of the service",paragraphs:["AirCapital is a read-only portfolio monitoring utility. It does not hold customer assets, perform trading or initiate withdrawals. Names of exchanges identify supported integrations and do not imply affiliation or endorsement."]},
      {id:"documents",title:"Related documents",paragraphs:["Read the following documents for the conditions of use and information about personal data."],links:[{label:"Privacy policy",href:"/privacy"},{label:"Terms of use",href:"/terms"},{label:"Cookies and analytics",href:"/cookies"},{label:"Data deletion",href:"/data-deletion"}]},
    ],
  },
};
